import React from 'react';
import Head from 'next/head';
import Users from '../components/UsersControllees';
import { listUser } from "../components/functions/users";
const Home: React.FC = () => {
  
  
  return (
    <div>
      <Head>
        <title>VNDA Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Users />
      </main>

    </div>
  )
}


export default Home;